version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.1
      - image: mongo:4.0.3

    working_directory: ~/phone-book
    steps:
      - attach_workspace:
          at: ~/phone-book
    steps:
      - checkout

      - run:
          name: install-npm
          command: npm install
      - run:
          name: test
          command: npm test
